const ActionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",

  INCREMENTBY: "INCREMENTBY",
  DECREMENTBY: "DECREMENTBY",

  INCREMENTPROMPT: "INCREMENTPROMPT",
  DECREMENTPROMPT: "DECREMENTPROMPT",

}

export default ActionTypes;